# Generated by Django 4.0.3 on 2022-03-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_user_alter_message_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
    ]
