# Generated by Django 4.0.3 on 2022-03-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
