# Generated by Django 2.2.27 on 2022-03-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220309_1608'),
        ('chat', '0007_remove_message_room'),
    ]

    operations = [
    ]
