# Generated by Django 4.0.3 on 2022-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180410_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='received_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
